### ISSUE TITLE
Numbers not working in latest releases of remark

### ISSUE THREAD

**Issue by jlengstorf** [jlengstorf/gatsby-remark-numbered-footnotes#9]
Since https://github.com/syntax-tree/mdast-util-to-hast/pull/31, footnotes use `node.label` instead of `node.identifier`. This means that numbered footnotes aren't actually working right now.

An upstream fix is required, and the PR is open: https://github.com/zestedesavoir/zmarkdown/pull/362

As soon as that merges, we need to bump to the updated version and cut a new release of this plugin to fix. This will fix https://github.com/gatsbyjs/gatsby/issues/16578

**Comment by ghost** [comment]
remark-numbered-footnotes@1.1.0 seems to fix the problem. But for some reason I keep getting remark-numbered-footnotes@1.0.12 installed when I create a new Gatsby site, in spite of this plugin marking remark-numbered-footnotes@^1.0.1 as devDep. So it should include v1.1.0. Not sure why you need to bump the version of this plugin? Maybe someone could elaborate? Thanks!

**Comment by ghost** [comment]
Lockfile! Ofc! 🙈
